### ISSUE TITLE
Compass Image not loading

### ISSUE THREAD

**Issue by 1414841886** [matvey-koz/geofs-hud#1]
![image](https://github.com/matvey-koz/geofs-hud/assets/154767397/6b8fbe90-b7e2-48fb-9fe9-dbf9c96322ad)

**Comment by matvey-koz** [comment]
Yes, it doesn't work because I changed the image path I'm still fixing it.

**Comment by 1414841886** [comment]
> Yes, it doesn't work because I changed the image path I'm still fixing it.
> 
> **Edit**: You should be able to see it properly now, I updated the images and changed the size of the compass

ok If you finish please tell me Thanks
